"use client";

import { useEffect, useState } from "react";

interface State {
  loading: boolean;
  text: string | null;
  model: string | null;
  enabled: boolean;
}

export default function CoachNote() {
  const [s, setS] = useState<State>({
    loading: true,
    text: null,
    model: null,
    enabled: true,
  });

  useEffect(() => {
    let cancelled = false;
    fetch("/api/coach/narrative")
      .then((r) => r.json())
      .then((d) => {
        if (cancelled) return;
        setS({ loading: false, text: d.text ?? null, model: d.model ?? null, enabled: d.enabled !== false });
      })
      .catch(() => {
        if (!cancelled) setS((p) => ({ ...p, loading: false }));
      });
    return () => {
      cancelled = true;
    };
  }, []);

  // If AI isn't configured, render nothing — the cited plan stands on its own.
  if (!s.enabled || (!s.loading && !s.text)) return null;

  return (
    <div className="glass p-5">
      <div className="flex items-center gap-2">
        <span className="grid h-6 w-6 place-items-center rounded-md bg-accent-weak text-xs">
          ✦
        </span>
        <h2 className="text-sm font-semibold uppercase tracking-wide text-fg-muted">
          Coach&apos;s note
        </h2>
      </div>
      {s.loading ? (
        <p className="mt-3 animate-pulse text-sm text-fg-subtle">
          Writing your personalized note…
        </p>
      ) : (
        <>
          <p className="mt-3 text-sm leading-relaxed text-fg">{s.text}</p>
          {s.model && (
            <p className="mt-2 text-[11px] text-fg-subtle">
              Generated by {s.model} · grounded in STRATUM&apos;s research library
            </p>
          )}
        </>
      )}
    </div>
  );
}
